server = "127.0.0.1:51820"                                                                                                 
private_key = ""                                                                                                           
server_public_key = "n/dkMF66Ci2Z9f2+cjkFaGsVfLj1Da20WFeNP8XkrSY="