server = "127.0.0.1:51820"                                                                                                 
private_key = ""                                                                                                           
server_public_key = "JPgIlCMF2mN2MsDI9cjGKXNsnTnhgUFAWfzGjd4X1VI="